import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { Providers } from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PROJECT-L",
  description: "Generated by Network Science",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const pathname = typeof window !== "undefined" ? window.location.pathname : "";

  // Hide Navbar for /s/* routes
  const hideNavbar = pathname.startsWith("/s/");
  return (
    <ClerkProvider>
      <Providers>
          <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased grainy min-h-screen`}>
              <div className="flex h-screen">
                <div className="flex-1 flex flex-col"> {/* Width matches Sidebar width */}
                  {!hideNavbar&&<Navbar />}
                  <main className="flex-1 overflow-y-auto">
                    {children}
                  </main>
                </div>
              </div>
              <Toaster />
            </body>
          </html>
      </Providers>
    </ClerkProvider>
  );
}