import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import NavbarWrapper from "@/components/NavbarWrapper";
import { Providers } from "@/components/Providers";

// Configure Geist font families for consistent typography
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Global metadata for SEO
export const metadata: Metadata = {
  title: "PROJECT-L",
  description: "Generated by Network Science",
};
// Root layout component - wraps all pages with common providers and layout structure
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased grainy min-h-screen`}>
            <div className="flex h-screen">
              <div className="flex-1 flex flex-col"> {/* Width matches Sidebar width */}
                <NavbarWrapper />
                <main className="flex-1 overflow-y-auto">
                  {children}
                </main>
              </div>
            </div>
            <Toaster />
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}